--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisukeTeam/BuyLand
build-by-default: true
branches:
- main
projects:
  BuyLand:
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: pjz9n/libi18n/libi18n
        version: ^0.0.1
      - src: CortexPE/Commando/Commando
        version: ^2.1.1
...
